'use strict';

const DEFAULT_USER_AGENT = 'iobroker.waipu/0.0.1';
const SLOT_HOURS = 4;
const TOKEN_REFRESH_THRESHOLD_SEC = 60;
const EPG_LOOKAHEAD_HOURS = 6;
const EPG_LOOKBEHIND_MINUTES = 30;

module.exports = {
    DEFAULT_USER_AGENT,
    SLOT_HOURS,
    TOKEN_REFRESH_THRESHOLD_SEC,
    EPG_LOOKAHEAD_HOURS,
    EPG_LOOKBEHIND_MINUTES,
};
